services:
    admin_microservice_laravel:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'admin_microservice_sail-8.4/app'
        container_name: admin_microservice_laravel
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '81:80' # Changed to a different port to avoid conflict with main_microservice
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - admin_microservice_mysql

    admin_microservice_mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: admin_microservice_mysql
        ports:
            - '3308:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'admin_microservice_sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    admin_microservice_phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: admin_microservice_phpmyadmin
        ports:
            - '8083:80'
        environment:
            PMA_HOST: admin_microservice_mysql
            PMA_PORT: 3306
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        depends_on:
            - admin_microservice_mysql
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    admin_microservice_sail-mysql:
        driver: local
